# ls-lint configuration for file and folder naming conventions
# https://ls-lint.org/

ls:
  # Source files - language-specific conventions
  src:
    .js: camelCase | PascalCase
    .jsx: PascalCase                    # React components
    .ts: camelCase | PascalCase
    .tsx: PascalCase                    # React components
    .py: snake_case
    .go: snake_case
    .rs: snake_case
    .c: snake_case
    .cpp: snake_case | camelCase
    .h: snake_case | camelCase

  # Test files - descriptive kebab-case or snake_case
  tests:
    .test.js: kebab-case | camelCase
    .test.ts: kebab-case | camelCase
    .spec.js: kebab-case | camelCase
    .spec.ts: kebab-case | camelCase
    .test.py: snake_case
    .spec.py: snake_case

  # Test directories
  __tests__:
    .js: camelCase | PascalCase
    .ts: camelCase | PascalCase
    .py: snake_case

  # Documentation - kebab-case or SCREAMING
  docs:
    .md: kebab-case | SCREAMING-SNAKE-CASE  # README, CHANGELOG, etc.
    .rst: kebab-case

  # Configuration files - kebab-case or dotfiles
  .:
    .json: kebab-case | regex:^\.[a-z]+
    .yaml: kebab-case | regex:^\.[a-z]+
    .yml: kebab-case | regex:^\.[a-z]+
    .toml: kebab-case | regex:^\.[a-z]+
    .ini: kebab-case
    .cfg: kebab-case
    .conf: kebab-case
    .config.js: kebab-case
    .config.ts: kebab-case

  # Scripts - kebab-case
  scripts:
    .sh: kebab-case
    .bash: kebab-case
    .zsh: kebab-case
    .fish: kebab-case
    .py: kebab-case | snake_case

  # Build output - allow any (generated files)
  dist:
    .js: regex:.*
    .css: regex:.*
    .html: regex:.*

  build:
    .js: regex:.*
    .css: regex:.*

  # Quality reports - snake_case
  .quality:
    .json: kebab-case | snake_case
    .txt: kebab-case | snake_case
    .md: kebab-case

  # Directories - kebab-case everywhere
  .dir: kebab-case | snake_case

# Files and directories to ignore
ignore:
  - node_modules
  - .devenv
  - .direnv
  - .git
  - dist
  - build
  - coverage
  - .coverage
  - .nyc_output
  - .pytest_cache
  - __pycache__
  - .venv
  - venv
  - .env
  - result
  - result-*

# Special exceptions (files that don't follow rules)
# These are typically root-level configuration files
# No action needed - ls-lint auto-ignores common patterns
